import os

secrets_file = ".streamlit/secrets.toml"
os.makedirs(os.path.dirname(secrets_file), exist_ok=True)

with open(secrets_file, "w") as file:
    file.write("[env]\n")
    file.write("OPENAI_API_KEY = \"your_api_key\"\n")
